### PR TITLE
Proposed changes to Taxonium integration

### PR DESCRIPTION
**Pull request by theosanderson**
(Super cool! Reply coming in my issue!)

It's probably better to use the mpx.taxonium.org URL which includes the config stuff by default. I haven't tested this PR :/

### CODE REVIEW

**Comment by theosanderson** [comment]
One could potentially remove the `control:true` as well, which will mean you don't have the option to do inexact or multiple searches, but that's probably not useful here

**Comment by chaoran-chen** [comment]
Thanks! Could you please just update your branch? I made another change right before your PR: https://github.com/cevo-public/mpox-spectrum-website/commit/85d4995e7f5f2f2a93f04f892399291dfc6539c4

**Comment by theosanderson** [comment]
Ah, interesting that GitHub doesn't check for underlying changes when you edit with the basic "Edit this file" web thingie!

Hopefully this works. Additionally:
- now removed the controls (but we can revert that if you prefer)
- updated the "None" so that it selects the right menu item

**Comment by theosanderson** [comment]
And thanks for wrestling with figuring out the confusing Taxonium parameters :)

**Review by chaoran-chen — APPROVED** [review]
Thank you!

**Pull request merged**
